[project]
authors = ["PaulKMueller <paul.mueller@quantco.com>"]
channels = ["conda-forge"]
description = "Add a short description here"
name = "sus_hackathon"
platforms = ["osx-arm64", "linux-64", "win-64"]
version = "0.1.0"

[tasks]
streamlit = "streamlit run main.py"

[dependencies]
streamlit = ">=1.39.0,<2"
geopy = ">=2.4.1,<3"
area = ">=1.1.1,<2"
pandas = ">=2.2.3,<3"
pydeck = ">=0.8.0,<0.9"
scipy = ">=1.14.1,<2"
